// Next.js metadata type used for type-safe SEO configuration
import type { Metadata } from "next";

// Importing Google fonts via Next.js built-in font optimization system
// These fonts are loaded efficiently and automatically optimized (no manual CSS import needed)
import { Geist, Geist_Mono } from "next/font/google";

// Global CSS file (applies styles across the entire app)
import "./globals.css";

// -----------------------------
// Font setup (CSS variable-based)
// -----------------------------

// Sans-serif font (main UI font)
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name you can use in Tailwind or CSS
  subsets: ["latin"], // only load Latin characters to reduce bundle size
});

// Monospace font (for code, logs, technical UI, etc.)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for monospace font
  subsets: ["latin"],
});

// -----------------------------
// App metadata (SEO + browser tab info)
// -----------------------------

export const metadata: Metadata = {
  title: "Create Next App", // Appears in browser tab + search engines
  description: "Generated by create next app", // SEO description for search engines
};

// -----------------------------
// Root layout (wraps every page in the app)
// -----------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // All pages/components inside the app are passed here
}>) {
  return (
    // <html> is the top-level document element in Next.js App Router
    <html
      lang="en" // language for accessibility + SEO
      className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        h-full 
        antialiased
      `}
    >
      {/*
        What this className does:
        - geistSans.variable → makes "--font-geist-sans" available globally
        - geistMono.variable → makes "--font-geist-mono" available globally
        - h-full → ensures html takes full viewport height
        - antialiased → improves font rendering (smoother text edges)
      */}

      <body className="min-h-full flex flex-col">
        {/*
          body styles:
          - min-h-full → ensures body fills at least full screen height
          - flex flex-col → sets vertical layout for app structure
            (useful for layouts like header → content → footer)
        */}

        {children}
        {/*
          This is where all pages render.
          In Next.js App Router, every route is injected here.
        */}
      </body>
    </html>
  );
}
